### ISSUE TITLE
Season 14 Virus Detection

### ISSUE THREAD

**Issue by 5eamu5** [MaciejGorczyca/ChallengesAreEvil#18]
As of 10/1/2024, whenever I try to download my antivirus goes off. Not sure if this is because of the new season or something else.

**Comment by kovimilu** [comment]
I am pretty sure it is unrelated to the new season.
You could try disabling your antivirus (i don't personally recommend) or compiling the repo yourself.

I just tried the PowerShell script and that still works fine (win 10) if all you are looking for is to remove the Tokens i would recommend giving that a try.

**Comment by MaciejGorczyca** [comment]
Hey. The file didn't change for many months. The season has nothing to do with the app. Also more info about false positive detection here https://github.com/MaciejGorczyca/ChallengesAreEvil/issues/8

You can try to whitelist the file or use alternative methods like the one mentioned above. Good luck!
