### ISSUE TITLE
Border remover

### ISSUE THREAD

**Issue by SgtBlade** [MaciejGorczyca/ChallengesAreEvil#2]
Any chance you'll make a border remover?

**Comment by MaciejGorczyca** [comment]
If you explain or provide tutorial how I can do that then sure because I have no idea how to do that (if it isn't already a feature in the client).

**Comment by SgtBlade** [comment]
I have no idea how to do it. From what I found online League support is able to remove it so I thought it might be possible to do it like you did the challenges. 

How were you able to find the right command to turn off the challenges?

**Comment by MaciejGorczyca** [comment]
I found [step by step explanation how to remove tokens here](https://www.reddit.com/r/leagueoflegends/comments/w91xqk/patch_1214_bug_megathread/iip126n/) but if you ever find out how to remove borders let me know here or send an email!
