### ISSUE TITLE
can no longer use tokens at all

### ISSUE THREAD

**Issue by pmetemp** [MaciejGorczyca/ChallengesAreEvil#6]
I used this tool to remove tokens from my profile so that I could use only 1 token in the center.

All tokens are removed from the profile but now I cannot use any tokens at all even if I restart the client.
Selecting a token causes the "customize identity" window to be unable to close, requiring a restart.

**Comment by MaciejGorczyca** [comment]
If something breaks then it is because of Riot and the changes in the client. App functionality is the same as it ever was and it correctly removes tokens. Try contacting Riot and telling them how awful tokens are but don't expect them to listen.
