### ISSUE TITLE
how can i stop the program after i use it?

### ISSUE THREAD

**Issue by uusubi** [MaciejGorczyca/ChallengesAreEvil#9]
i just wanted to use this app to remove my tokens and then just equip 1 but i wont allow me to i can't even close the profile tab when i try. so i wanted to try deleting the app/uninstalling it but it still wont let me choose a token when i did.

**Comment by MaciejGorczyca** [comment]
You can't select one token. If you want to do that then contact Riot and tell them you really want to do that and they should modify client to let you equip only one.
